package com.lexwilliam.dependencies

object Versions {
    const val core = "1.15.0"
    const val material = "1.4.0"
    const val compose = "2025.05.00"
    const val composeSystemUi = "0.24.3-alpha"
    const val composeNavigation = "2.4.0-beta01"
    const val googleSecret = "2.0.1"
    const val hilt = "2.51.1"
    const val hiltVM = "1.2.0"
    const val androidxTest = "1.2.0"
    const val espresso = "3.4.0"
    const val androidxJunit = "1.1.1"
    const val junit = "4.13.1"
    const val junitPlatformRunner = "1.0.2"
    const val mockito = "3.12.3"
    const val mockitoKotlin = "1.6.0"
    const val gradle = "8.11.0"
    const val kotlin = "2.0.0"
    const val timber = "4.7.1"
    const val lottie = "4.2.0"
    const val lottieCompose = "4.2.1"
    const val coreTesting = "1.1.1"
    const val room = "2.7.2"
    const val retrofit = "2.6.2"
    const val moshi = "1.11.0"
    const val okhttpLoggingInterceptor = "4.9.1"
    const val coil = "2.0.0-rc01"
    const val jodaTime = "2.10.8"
    const val truth = "1.1.3"
    const val mockWebServer = "4.9.0"
    const val browser = "1.4.0"
    const val kotlinxCoroutines = "1.6.0"
    const val retrofitCoroutineAdapter = "0.9.2"
    const val robolectric = "4.8.1"
    const val accompanist = "0.24.3-alpha"
    const val splashScreen = "1.0.0-beta02"
}