package com.lexwilliam.risutov2.model.detail

import com.lexwilliam.risutov2.model.common.*

data class AnimeDetailPresentation(
    val aired: AiredPresentation? = AiredPresentation("", PropPresentation(FromPresentation(-1, -1, -1), ToPresentation(-1, -1, -1)), "", ""),
    val airing: Boolean? = false,
    val background: Any? = "",
    val broadcast: String? = "",
    val duration: String? = "",
    val ending_themes: List<String>? = emptyList(),
    val episodes: Int? = -1,
    val favorites: Int? = -1,
    val genres: List<GenrePresentation>? = emptyList(),
    val image_url: String? = "",
    val licensors: List<LicensorPresentation>? = emptyList(),
    val mal_id: Int? = -1,
    val members: Int?= -1,
    val opening_themes: List<String>? = emptyList(),
    val popularity: Int? = -1,
    val premiered: String? = "",
    val producers: List<ProducerPresentation>? = emptyList(),
    val rank: Int? = -1,
    val rating: String? = "",
    val related: RelatedPresentation? = RelatedPresentation(),
    val request_cache_expiry: Int? = -1,
    val request_cached: Boolean? = false,
    val request_hash: String? = "",
    val score: Double? = -1.0,
    val scored_by: Int? = -1,
    val source: String? = "",
    val status: String? = "",
    val studios: List<StudioPresentation>? = emptyList(),
    val synopsis: String? = "",
    val title: String? = "",
    val title_english: Any? = "",
    val title_japanese: String? = "",
    val title_synonyms: List<Any>? = emptyList(),
    val trailer_url: String? = "",
    val type: String? = "",
    val url: String? = ""
)