package com.example.risuto.presentation.util

import com.example.risuto.presentation.model.custom.GridStylePresentation
import com.example.risuto.presentation.model.custom.RowStylePresentation

fun generateFakeGridItem(): GridStylePresentation{
    return GridStylePresentation(1, "", "Wonder Egg Priority", "TV", 7, 9.1f, 1000000)
}

fun generateFakeGridItemList(): List<GridStylePresentation> {
    return listOf(
        GridStylePresentation(1, "", "Wonder Egg Priority", "TV", 7, 9.1f, 1000000),
        GridStylePresentation(1, "", "Wonder Egg Priority", "TV", 7, 9.1f, 1000000),
        GridStylePresentation(1, "", "Wonder Egg Priority", "TV", 7, 9.1f, 1000000),
        GridStylePresentation(1, "", "Wonder Egg Priority", "TV", 7, 9.1f, 1000000),
        GridStylePresentation(1, "", "Wonder Egg Priority", "TV", 7, 9.1f, 1000000),
        GridStylePresentation(1, "", "Wonder Egg Priority", "TV", 7, 9.1f, 1000000),
        GridStylePresentation(1, "", "Wonder Egg Priority", "TV", 7, 9.1f, 1000000),
        GridStylePresentation(1, "", "Wonder Egg Priority", "TV", 7, 9.1f, 1000000)
    )
}

fun generateFakeRowItem(): RowStylePresentation{
    return RowStylePresentation(1, "", "Wonder Egg Priority", "Following the suicide of her best and only friend, Koito Nagase, Ai Ooto is left grappling with her new reality. With nothing left to live for, she follows the instructions of a mysterious entity and gets roped into purchasing an egg, or specifically, a Wonder Egg.\n" + "\n" + "Upon breaking the egg in a world that materializes during her sleep, Ai is tasked with saving people from the adversities that come their way. In doing so, she believes that she has moved one step closer to saving her best friend. With this dangerous yet tempting opportunity in the palms of her hands, Ai enters a place where she must recognize the relationship between other people's demons and her own.\n" + "\n" + "As past trauma, unforgettable regrets, and innate fears hatch in the bizarre world of Wonder Egg Priority, a young girl discovers the different inner struggles tormenting humankind and rescues them from their worst fears.\n" + "\n" + "[Written by MAL Rewrite]","TV", 7, 9.1f, 1000000)
}

fun generateFakeRowItemList(): List<RowStylePresentation> {
    return listOf(
        RowStylePresentation(1, "", "Wonder Egg Priority", "Following the suicide of her best and only friend, Koito Nagase, Ai Ooto is left grappling with her new reality. With nothing left to live for, she follows the instructions of a mysterious entity and gets roped into purchasing an egg, or specifically, a Wonder Egg.\n" + "\n" + "Upon breaking the egg in a world that materializes during her sleep, Ai is tasked with saving people from the adversities that come their way. In doing so, she believes that she has moved one step closer to saving her best friend. With this dangerous yet tempting opportunity in the palms of her hands, Ai enters a place where she must recognize the relationship between other people's demons and her own.\n" + "\n" + "As past trauma, unforgettable regrets, and innate fears hatch in the bizarre world of Wonder Egg Priority, a young girl discovers the different inner struggles tormenting humankind and rescues them from their worst fears.\n" + "\n" + "[Written by MAL Rewrite]","TV", 7, 9.1f, 1000000),
        RowStylePresentation(1, "", "Wonder Egg Priority", "Following the suicide of her best and only friend, Koito Nagase, Ai Ooto is left grappling with her new reality. With nothing left to live for, she follows the instructions of a mysterious entity and gets roped into purchasing an egg, or specifically, a Wonder Egg.\n" + "\n" + "Upon breaking the egg in a world that materializes during her sleep, Ai is tasked with saving people from the adversities that come their way. In doing so, she believes that she has moved one step closer to saving her best friend. With this dangerous yet tempting opportunity in the palms of her hands, Ai enters a place where she must recognize the relationship between other people's demons and her own.\n" + "\n" + "As past trauma, unforgettable regrets, and innate fears hatch in the bizarre world of Wonder Egg Priority, a young girl discovers the different inner struggles tormenting humankind and rescues them from their worst fears.\n" + "\n" + "[Written by MAL Rewrite]","TV", 7, 9.1f, 1000000),
        RowStylePresentation(1, "", "Wonder Egg Priority", "Following the suicide of her best and only friend, Koito Nagase, Ai Ooto is left grappling with her new reality. With nothing left to live for, she follows the instructions of a mysterious entity and gets roped into purchasing an egg, or specifically, a Wonder Egg.\n" + "\n" + "Upon breaking the egg in a world that materializes during her sleep, Ai is tasked with saving people from the adversities that come their way. In doing so, she believes that she has moved one step closer to saving her best friend. With this dangerous yet tempting opportunity in the palms of her hands, Ai enters a place where she must recognize the relationship between other people's demons and her own.\n" + "\n" + "As past trauma, unforgettable regrets, and innate fears hatch in the bizarre world of Wonder Egg Priority, a young girl discovers the different inner struggles tormenting humankind and rescues them from their worst fears.\n" + "\n" + "[Written by MAL Rewrite]","TV", 7, 9.1f, 1000000),
        RowStylePresentation(1, "", "Wonder Egg Priority", "Following the suicide of her best and only friend, Koito Nagase, Ai Ooto is left grappling with her new reality. With nothing left to live for, she follows the instructions of a mysterious entity and gets roped into purchasing an egg, or specifically, a Wonder Egg.\n" + "\n" + "Upon breaking the egg in a world that materializes during her sleep, Ai is tasked with saving people from the adversities that come their way. In doing so, she believes that she has moved one step closer to saving her best friend. With this dangerous yet tempting opportunity in the palms of her hands, Ai enters a place where she must recognize the relationship between other people's demons and her own.\n" + "\n" + "As past trauma, unforgettable regrets, and innate fears hatch in the bizarre world of Wonder Egg Priority, a young girl discovers the different inner struggles tormenting humankind and rescues them from their worst fears.\n" + "\n" + "[Written by MAL Rewrite]","TV", 7, 9.1f, 1000000),
        RowStylePresentation(1, "", "Wonder Egg Priority", "Following the suicide of her best and only friend, Koito Nagase, Ai Ooto is left grappling with her new reality. With nothing left to live for, she follows the instructions of a mysterious entity and gets roped into purchasing an egg, or specifically, a Wonder Egg.\n" + "\n" + "Upon breaking the egg in a world that materializes during her sleep, Ai is tasked with saving people from the adversities that come their way. In doing so, she believes that she has moved one step closer to saving her best friend. With this dangerous yet tempting opportunity in the palms of her hands, Ai enters a place where she must recognize the relationship between other people's demons and her own.\n" + "\n" + "As past trauma, unforgettable regrets, and innate fears hatch in the bizarre world of Wonder Egg Priority, a young girl discovers the different inner struggles tormenting humankind and rescues them from their worst fears.\n" + "\n" + "[Written by MAL Rewrite]","TV", 7, 9.1f, 1000000),
        RowStylePresentation(1, "", "Wonder Egg Priority", "Following the suicide of her best and only friend, Koito Nagase, Ai Ooto is left grappling with her new reality. With nothing left to live for, she follows the instructions of a mysterious entity and gets roped into purchasing an egg, or specifically, a Wonder Egg.\n" + "\n" + "Upon breaking the egg in a world that materializes during her sleep, Ai is tasked with saving people from the adversities that come their way. In doing so, she believes that she has moved one step closer to saving her best friend. With this dangerous yet tempting opportunity in the palms of her hands, Ai enters a place where she must recognize the relationship between other people's demons and her own.\n" + "\n" + "As past trauma, unforgettable regrets, and innate fears hatch in the bizarre world of Wonder Egg Priority, a young girl discovers the different inner struggles tormenting humankind and rescues them from their worst fears.\n" + "\n" + "[Written by MAL Rewrite]","TV", 7, 9.1f, 1000000),
        RowStylePresentation(1, "", "Wonder Egg Priority", "Following the suicide of her best and only friend, Koito Nagase, Ai Ooto is left grappling with her new reality. With nothing left to live for, she follows the instructions of a mysterious entity and gets roped into purchasing an egg, or specifically, a Wonder Egg.\n" + "\n" + "Upon breaking the egg in a world that materializes during her sleep, Ai is tasked with saving people from the adversities that come their way. In doing so, she believes that she has moved one step closer to saving her best friend. With this dangerous yet tempting opportunity in the palms of her hands, Ai enters a place where she must recognize the relationship between other people's demons and her own.\n" + "\n" + "As past trauma, unforgettable regrets, and innate fears hatch in the bizarre world of Wonder Egg Priority, a young girl discovers the different inner struggles tormenting humankind and rescues them from their worst fears.\n" + "\n" + "[Written by MAL Rewrite]","TV", 7, 9.1f, 1000000)
    )
}